server:
  port: 8800

eureka:
  instance:
    hostname: peer1
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://peer2:8815/eureka/
  server:
    enable-self-preservation: false

spring:
  application:
    name: eurka-server

